import { createContext, useState, useMemo } from 'react';

//create a context, with createContext api
export const employeesContext = createContext();

const AllEmployeesProvider = (props) => {
    // this state will be shared with all components 
    
    const [allEmployees, setEmployee] = useState([{
        firstName : "Test",
        lastName : "User00",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User01",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User02",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User03",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User04",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User05",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User06",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User07",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User08",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User09",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User10",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User11",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User12",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User13",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User14",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User15",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User16",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User17",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User18",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User19",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User20",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User21",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User22",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User23",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User24",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User25",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User26",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User27",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User28",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    },{
        firstName : "Test",
        lastName : "User29",
        dateOfBirth: "2020-10-15",
        startDate : "2020-10-15",
        addressStreet: "A Random Street",
        addressCity: "Random City",
        addressState: "AL",
        addressZip: "12345",
        employeeDepartment: "Sales",
    }]);
    const value = useMemo(() => ({
        allEmployees, setEmployee
    }), [allEmployees, setEmployee]);
    return (
        // this is the provider providing state
        <employeesContext.Provider value={value}>
            {props.children}
        </employeesContext.Provider>
    );
};

export default AllEmployeesProvider;